name: Test
on:
  push:
jobs:
  test-project:
    name: Test Project
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Configure and Build Project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true
