name: CPP Configure and Build Test
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build PracticeCPP
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up CMake
        uses: actions/setup-cmake@v3
        with:
          cmake-version: '3.30.1'  # Ensure this version matches your project requirements

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: cmake --build build
